### ISSUE TITLE
Menu overlay

### ISSUE THREAD

**Issue by letsjustfixit** [TryGhost/Casper#180]
Hy Team,

There is a small z-index bug in the theme on the front-page:

![partial screenshot](http://i.imgur.com/NV79ajH.png)
If the menu is opened then the original link overlaps the navigation bar title "Menu"

v0.5.9

**Comment by JohnONolan** [comment]
This was fixed in https://github.com/TryGhost/Casper/commit/8b35959ff6af9e8a449b200016e7b9a1cfa66041

**Comment by letsjustfixit** [comment]
Well after that (and only that) change the menu link doesnt work anymore (i guess overlay issue the other way around :). so this didnt fix the issue rather made it worse (now you cant open the menu)

Duplicate of issue #178

**Comment by JohnONolan** [comment]
@letsjustfixit Did that ^ change work for you?

**Comment by letsjustfixit** [comment]
@JohnONolan yepp it works as it should :smile: 
@PaulAdamDavis :doughnut:  ;)
